### ISSUE TITLE
TEST(PathFinder, corner_squeezing) {

### ISSUE THREAD

**Issue by TvdBrink** [HU-R2D2/pathfinding#1]
for (int x = 0; x < 10; x++) {
        std::vector<int> current;
        for (int y = 0; y < 10; y++) {
            if (x == y) {
                current.push_back(1);
            } else {
                current.push_back(0);
            }
            cornerSqueezeMap.push_back(current);
        }
    }

conerSqueezeMap.push_back(current); moet worden geswapt met de lijn er onder.

**Comment by chieltbest** [comment]
fixed in commit 9e87b1be94f2ea9e19dd57a6ec7efcb583cd02d1
