### ISSUE TITLE
print_map() function in dummy.hpp

### ISSUE THREAD

**Issue by TvdBrink** [HU-R2D2/pathfinding#2]
Het afdrukken van map gebeurd in spiegelbeeld. De correcte code is:
void Map::print_map() {
        for (int i1 = 0; i1 < sizeY; i1++) {
            for (int i2 = 0; i2 < sizeX; i2++) {
                std::cout << map[i2][i1];
            }
            std::cout << std::endl;
        }
    }

**Comment by chieltbest** [comment]
fixed in commit 9e87b1be94f2ea9e19dd57a6ec7efcb583cd02d1
