### ISSUE TITLE
Pathfinding efficiency

### ISSUE THREAD

**Issue by TvdBrink** [HU-R2D2/pathfinding#3]
De heuristics van de AStarPathFinder zijn niet efficiënt. 
afbeelding 1: het blauwe path is het resultaat van de pathfinder, terwijl het efficientste path het rode path zou zijn. de output coordinaten van het blauwe path zijn zichtbaar op afbeelding 2.
![pathfinderissue](https://cloud.githubusercontent.com/assets/14776660/15859942/6b34e954-2cc7-11e6-9fdd-0b69d8a13e6b.PNG)
![pathfinderissue2](https://cloud.githubusercontent.com/assets/14776660/15859943/6b4777cc-2cc7-11e6-9184-f692c9d89c26.PNG)

**Comment by chieltbest** [comment]
fixed in commit 9e87b1be94f2ea9e19dd57a6ec7efcb583cd02d1
